[package]
name = "registry"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = { workspace = true }
bytes = "1.5.0"

[dev_dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
