[workspace]
resolver = "2"

members = ["test_utils", "common", "contracts/*", "tests"]

[workspace.dependencies]
soroban-sdk = "23.3.0"

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

[profile.release-with-logs]
inherits = "release"
debug-assertions = true
