name: Build and Release Reverse Registrar contract
on:
  workflow_dispatch:
    inputs:
      release_name:
        description: "Unique release name"
        required: true
        type: string

  push:
    tags:
      - reverse-registrar-v*

jobs:
  release-reverse-registrar:
    uses: stellar-expert/soroban-build-workflow/.github/workflows/release.yml@4d0117fd348fb90cc36e2cd8c774f822802752af
    with:
      release_name: ${{ github.ref_name }}
      release_description: "ReverseRegistrar contract"
      relative_path: '["contracts/reverse-registrar"]'
      package: "reverse-registrar"
      make_target: "build"
    secrets: # the authentication token will be automatically created by GitHub
      release_token: ${{ secrets.GITHUB_TOKEN }}
